# Generated by Django 3.2.5 on 2021-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
                ('page_url', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('page_id', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('number_reviews', models.IntegerField()),
                ('affiliat_id', models.CharField(max_length=200)),
                ('product_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Similar_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('link_number', models.IntegerField()),
                ('last_crawl', models.DateTimeField()),
                ('crawl_time', models.CharField(max_length=200)),
            ],
        ),
    ]
